### PR TITLE
Updates noscript settings to generate more reasonable FB preview.

### LINKED ISSUE #2799: Facebook sharing preview is terrible
**Current behavior**

Facebook's crawler does not support JS, so when one is sharing a link to Globaleaks instance on Facebook (and possibly other platforms), the link preview is just wrong. It shows the native message for the browser with disabled JS.

```
Warnings That Should Be Fixed

    Inferred Property
    The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.
    Missing Properties
    The following required properties are missing: og:url, og:type, og:title, og:image, og:description, fb:app_id
```

**Expected behavior**

Globaleaks should detect a robot browser and show a simplified HTML of the page which the robot tried to load. For example, when robot loads index page, it should show logo as og:image and TitleBox as og:title etc.

**Steps to reproduce the problem or feature illustration**

Try the link to Globaleaks instance at: https://developers.facebook.com/tools/debug/ 

**What is the motivation or use case for changing the behavior?**

One wants to raise awareness about the instance of Globaleaks so the people know about it and then will use it. One cool way is to let the people to spread the word through social networks. 

**GlobaLeaks version:**

**Browser:**

Firefox 74.0

**Server Operating System and Version (if applicable):**
 
Debian 10.3

**Client Operating System and Version (if applicable):**

Fedora 31

### PR DESCRIPTION
**Pull request by flosincapite**
Fixes #2799

### CODE REVIEW

**Comment by flosincapite** [comment]
Hi, all, I am trying to fix this but am stuck. I can run the backend locally with

```
cd GlobaLeaks/backend
./bin/globaleaks -z -n
```

I reverse-proxied this local deployment with nginx so I can generate a FaceBook preview. However, I've noticed that changes in client code aren't propagating (I changed the <noscript> tag's text in `client/app/index.html`, but it doesn't show up on my local deployment). 

I've removed cookies, so I don't think this is a caching problem.

Is there a way to run the client locally? If so, how do I point my backend to the local client? If not, why am I getting this behavior?

**Comment by evilaliv3** [comment]
Hello @flosincapite 

I'm happy you would like to contribute and work on this topic! Let me see where we can get together.

I guess that following the development guid you have 'built' the application that is the process required for releasing the application.
You can remove the directory 'build' from the client directory and restart globaleaks and you should see your changes.

**Comment by flosincapite** [comment]
Ah, excellent! That fixed it. Thank you so much! I'm going to be away for the weekend but will continue working on this next week.

**Comment by evilaliv3** [comment]
Thank you @flosincapite , is there any update on this?

**Comment by flosincapite** [comment]
Hi, all, apologies for the delay. I took on some contract work and haven't
had time this week. Realistically, I won't get to it until the weekend.
Happy to surrender the issue if someone would like to take it.

**Comment by evilaliv3** [comment]
That would be great! Thank you @flosincapite

**Pull request closed without merging**
