### PR TITLE
WIP: Add docker support

### LINKED ISSUE #692: Add Dockerfile to install with Docker
I've been looking into whether the install process could be simplified with Docker. The Dockerfile which I'm using sets up GlobaLeaks GLClient and GLBackend on an Ubuntu VM. I'm testing it on AWS -  the server runs, but ports aren't working yet. Once it does work, setting up GlobaLeaks it should just be as easy:

```
docker build -t globaleaks - < globaleaks.dockerfile
docker run -p 80:8082 -t globaleaks globaleaks/GLBackend/bin/globaleaks -z -d
```

or if it were included in the GitHub repo

```
docker build -t globaleaks - < github.com/globaleaks/GlobaLeaks
```

It's similar to #179 which was working on setting up GlobaLeaks using Vagrant.

Here's the Dockerfile:

```
# GlobaLeaks
#
# VERSION   1.0

# use ubuntu base image provided by dotCloud
FROM ubuntu

# install Python tools
RUN apt-get -y install python-software-properties

# install Tor
RUN add-apt-repository 'deb http://deb.torproject.org/torproject.org precise main'
RUN gpg --keyserver x-hkp://pool.sks-keyservers.net --recv-keys 0x886DDD89
RUN gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | apt-key add -
RUN apt-get update
RUN apt-get -y install tor tor-geoipdb curl

# set Tor to automatically start on boot
#RUN update-rc.d tor defaults

# install Python tools
RUN apt-get -y install git python-setuptools python-dev build-essential

# install and prepare pip
RUN easy_install pip
RUN pip install --upgrade pip
RUN pip install --upgrade virtualenv

# install GlobaLeaks requirements.txt
RUN pip install Twisted==13.1.0
RUN pip install apscheduler==2.1.1
RUN pip install zope.component==4.1.0
RUN pip install zope.interface==4.0.5
RUN pip install cyclone==1.1
RUN pip install Storm==0.20
RUN pip install transaction==1.4.1
RUN pip install txsocksx==1.13.0.0rc2
RUN pip install Parsley==1.2
RUN pip install pycrypto==2.6
RUN pip install scrypt==0.6.1
RUN pip install python_gnupg==0.3.5

# Prepare GlobaLeaks directory
RUN mkdir globaleaks

# Download GLBackend
RUN git clone https://github.com/globaleaks/GLBackend.git globaleaks/GLBackend
RUN export PYTHONPATH=`pwd`

# Install NodeJS
RUN echo "deb http://archive.ubuntu.com/ubuntu precise universe" >> /etc/apt/sources.list
RUN add-apt-repository ppa:chris-lea/node.js
RUN apt-get update
RUN apt-get -y install nodejs

# Download GLClient and build using Bower
RUN git clone https://github.com/globaleaks/GLClient.git globaleaks/GLClient
RUN npm install -g grunt-cli bower
RUN ( cd globaleaks/GLClient | bower update -f --allow-root )

# Configuring Tor - not yet set up

# give daemon permission on GlobaLeaks server
RUN chown -R daemon globaleaks/GLBackend
USER daemon
EXPOSE 8082
```
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1308236-add-dockerfile-to-install-with-docker?utm_campaign=plugin&utm_content=tracker%2F316378&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F316378&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ckeeney**
This pull request has 2 primary changes:

1. It adds the option `--allow-run-as-root` to simplify execution of GlobaLeaks in a Docker container.
2. It adds a `Dockerfile` and `docker-entrypoint.sh`.

Additionally, it adds a `docker-compose.yml` and adds an entry to `.gitignore` to avoid committing volumes used by `docker-compose.yml`.  The `docker-compose.yml` is not required for anything, but it makes a nice example for copy and paste, and makes it easier to develop and test the `Dockerfile`.

This PR is incomplete.  I can't connect to the container on port 80 or 443.  However, the Tor hidden service works so this PR is almost there.

Resolves #692

### CODE REVIEW

**Comment by ckeeney** [comment]
I am adding documentation on how to use this docker image here until we finalize a location for it.

To get started, install [docker](https://www.docker.com/).

`docker-compose` is not required, but it lets you configure `docker run ...` commands using a YAML file, which makes it much easier to run and rerun docker containers with the same CLI args.  You can download it [here](https://docs.docker.com/compose/install/).

The last thing you will need is to checkout this branch.  Since it has not been merged into this project yet, you will have to use [my fork of this project](https://github.com/ckeeney/GlobaLeaks/tree/add-docker-support).  You can either add it as a git remote to this project or clone my repo directly.  In my development environment, my `origin` remote points at this repository and my `ckeeney` remote points at my fork.

## With docker-compose
In the root of the project, you will find a `docker-compose.yml` file with the following contents:

```yaml
version: "3"
services:
  globaleaks:
    image: globaleaks
    build: .
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/var/:/var/globaleaks
```

From the project root directory, run `docker-compose up`.  If you want to run this docker container in the background, use `docker-compose up -d` instead.  The first time you run this command, docker will build the image.  Subsequent runs of this command will just reuse the most recent build.  If you want to rebuild the image, you can run `docker-compose up --build`.

Once the container is running, you can reach it at ports 80 and 443 of the host.

## Without docker-compose
If you choose not to use docker-compose, building a running the docker image are separate commands.
#### Build the docker image
From the project's root directory, run `docker build -t globaleaks .`. 
#### Run the docker image
To run the image we just built, we simply reference the name we used, `globaleaks`.  There are a number of args we must add to properly configure the container.
```bash
docker run --cap-add NET_ADMIN -v /host/directory/where/you/want/to/store/data:/var/globaleaks -p 80:80 -p 443:443 globaleaks
```
All data normally written to `/var/globaleaks` is written to the host at the location mounted into that volume of the container.  You can expose GlobaLeaks on different ports, for example 3000 by changing `-p 80:80` to `-p 3000:3000`.  However, the ACME protocol from Let's Encrypt requires communication over those ports so extra steps would be needed to get SSL working in that case.

For development, you can mount the project directory into `/usr/src/app` of the image and the changes you make to the source code of GlobaLeaks would be reflected in the container without having to rebuild the image.

**Comment by evilaliv3** [comment]
Hi @ckeeney, i'm sorry for being late reviewing this pull request.

Is there any recent change you would like to be integrated as well?

Here some comments for some changes we considered to require for integrating the patch:
- we consider fundamental to continue enabling to start globaleaks with the user "globaleaks"; internally we use that user both for apparmor and iptables and it is planned to use multiple different users still in relation to apparmor and iptables in order to fine tune the capabilities of the specific subprocesses.

- i see that you are executing globaleaks directly, instead of using "service globaleaks start" and you already explained me the reason; maybe after starting the service you can monitor the pid file to identify that the service shut down?

**Comment by n-daniel** [comment]
Hi all,

@ckeeney, for my containers i use both https://github.com/tianon/gosu and https://github.com/krallin/tini . Is tini enough for your needs ?
Regards
Daniel

**Comment by jaakkokorhonen** [comment]
Looks useful! Any plans to complete the pr?

**Comment by evilaliv3** [comment]
Yep @jaakkokorhonen; can you provide your feedback on this?

are you available for retesting?

**Comment by evilaliv3** [comment]
Closing as outdated; Code will be eventualy integrated manually while reworking on this topic.

**Pull request closed without merging**
