### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### globaleaks/GlobaLeaks now has a Chat Room on Gitter

@fpietrosanti has just created a chat room. You can visit it here: [https://gitter.im/globaleaks/GlobaLeaks](https://gitter.im/globaleaks/GlobaLeaks?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/globaleaks/GlobaLeaks?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by hellais** [comment]
Why do we have to create a bunch of chats that nobody will use?

Isn't it better to just focus on one communication medium per category, instead of risking to fragment the small community we have even further?

Pic related:

**Comment by evilaliv3** [comment]
its a nice way to take people on IRC, what is wrong with this?

**Comment by evilaliv3** [comment]
anyway @hellais  can you open me a pull for integrating the meme generator inside globaleak?

**Comment by hellais** [comment]
Ah ok sorry I thought this was ANOTHER chat system and not just an interface to an existing network.

Will thing about the meme generator thing.

**Pull request merged**
