### PR TITLE
Add "noopener" 

### PR DESCRIPTION
**Pull request by Taipo**
"noopener" sets any newly created browsing context which results from following the hyperlink, to disown its opener (since it's "_blank"), setting its window.opener property to null. Not particularly critical but doesn't hurt to do so.

### CODE REVIEW

**Comment by NSkelsey** [comment]
This is a great addition @Taipo.

There is also the link included in footer.html that is missing:
`<div id="AttributionClause" class="vcenter">Powered by <a href="https://www.globaleaks.org/" rel="noreferrer">GlobaLeaks</a></div>`

**Comment by fpietrosanti** [comment]
If it'a a privacy or security feature please document it in The document "application security design and Technical detail" explaining which is the possible risk it mitigate and how, or it does not exists 😘

**Comment by evilaliv3** [comment]
Importan addition @Taipo 

Sadly this is not a directive supproted by every browser so that we could investigate if other browsers have specific directives dealing with the issue: http://caniuse.com/#feat=rel-noopener

In the meantime i've cherry-picked your commits on the devel branch and all will be included in the next release! For this reason you see this pull request closed but anyhow the commits authored by you are here: https://github.com/globaleaks/GlobaLeaks/commits/devel

Next time when you prepare a pull request get sure to do it on the devel branch :)

**Comment by Taipo** [comment]
Firefox is the main one I was waiting for. It has been added and will be release next year . https://bugzilla.mozilla.org/show_bug.cgi?id=1222516

**Comment by NSkelsey** [comment]
@fpietrosanti [documented](https://docs.google.com/document/d/1SMSiAry7x5XY9nY8GAejJD75NWg7bp7M1PwXSiwy62U/pub) the addition.

**Comment by evilaliv3** [comment]
As this was integrated with a cherry-pick i'm now closing this pull request.

thanks @Taipo !

**Pull request closed without merging**
