### PR TITLE
sign?

### PR DESCRIPTION
**Pull request by flipchan**
add signing for stronger crypto + add verify signature

### CODE REVIEW

**Comment by evilaliv3** [comment]
what would be the added value?

thanks for your interest in contributing.

could you please open tickets and discuss your ideas instead of opening pull request with comments added to the code?

**Comment by flipchan** [comment]
well if you sign and encrypt the data, some extra security is added, so when you decrypt you first decrypt then verify the signature

**Comment by flipchan** [comment]
https://www.gnupg.org/gph/en/manual/x135.html

**Comment by evilaliv3** [comment]
Closing the pull request; TBD via ticket.

**Pull request closed without merging**
