### PR TITLE
Fixes and improvements to publiccode.yml

### PR DESCRIPTION
**Pull request by alranel**
In order to have this software included in the Developers Italia portal (released soon), a few tweaks to this publiccode.yml file were needed for better compatibility witht the 0.2 spec.

### CODE REVIEW

**Comment by evilaliv3** [comment]
Thank you @alranel !

Waiting for the test to complete in order to merge the patch!

Do you have any other recoendation that you suggest we follow on this topic?

**Comment by alranel** [comment]
The test failed but I think it's not my fault :-)

Regarding recommendation, you might want to add a couple screenshots to the publiccode.yml file so that it looks better in the catalog.

**Comment by evilaliv3** [comment]
Thank you for your suggestion @alranel.

I'm going to integrate your patch just right now.

I will take care of adding some before the catalog will be activated.

Which is my deadline? :)

**Comment by alranel** [comment]
No deadline! An automated crawler will take care of catching any updates. Please allow some delay, though. :)

**Pull request merged**
