### PR TITLE
First pass at implementing signup alert emails (fixes 2196)

### PR DESCRIPTION
**Pull request by NCommander**
Signed-off-by: Michael Casadevall <mcasadevall@ubuntu.com>

### CODE REVIEW

**Comment by evilaliv3** [comment]
Great start @NCommander ! thank you!

**Comment by evilaliv3** [comment]
@NCommander

I left you minor suggestions and some answer to your question on the ticket.

I've still not tried it but it look all right to me! well done!

**Comment by NCommander** [comment]
Fixed the typo in tab2.

There are still some issues with this PR so I don't recommend merging it yet; you commented before I could update the bug but I think I need to pipe down the L10n factory + userdata to the templating layer as I ran into a case where we need to dynamically load a translation into an email when using use_data.

**Comment by evilaliv3** [comment]
Integrated with very minor changes.

Thanks @NCommander !

**Pull request merged**
